language: node_js
node_js:
  - 0.8
  - 0.10

env:
  global:
  - SAUCE_USERNAME: vojtajina
  - secure: "F/q7B9PKan0RLtP69q4faqqmNrcmotCR1/MoghSA/+XgESZweH5SAkBiDCto9xHg4XtIkhKdS3GpenkYXRhaC9vuR+wdcZ/Hf68r1if9tmCgeRplGPyn1jLlpbkFDceXDXxlTBgM/GwqKvVOI5rKc/9X7IsjCS0aFlBD9+8doPY="

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - rm -rf node_modules/karma
  # TODO(vojta): remove once we use karma-dojo from NPM
  - cd node_modules/karma-dojo ; grunt build

script:
  - grunt
